language: android
sudo: false
jdk:
  - oraclejdk8
android:
  components:
    # Update Android SDK Tools
    - tools
    - platform-tools
    - tools
    - build-tools-28.0.3

    # Support library
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    - sys-img-armeabi-v7a-android-27
  script:
    - chmod +x ./gradlew
licenses:
    - 'android-sdk-license-.+'
    - 'android-sdk-preview-license-.+'
    - 'google-gdk-license-.+'
before_install:
  - yes | sdkmanager "platforms;android-27"
before_script:
- echo no | android create avd --force -n test -t "android-27" --abi $ANDROID_ABI --tag $ANDROID_TAG
  emulator -avd test -no-skin -no-audio -no-window &
  android-wait-for-emulator;
  sleep 10;
  adb shell svc power stayon true;
  sleep 5;
  adb shell input keyevent 82;
  ./gradlew --stacktrace connectedFdroidDebugAndroidTest -i;
