language: android
android:
  components:
    # Update Android SDK Tools
    - tools
    - platform-tools
    - tools
    - build-tools-26.0.2
    - android-26

    # Support library
    - extra-android-support
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-26
  script:
    - chmod +x ./gradlew
