language: android
android:
  components:
    # Update Android SDK Tools
    - tools
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-27

    # Support library
    - extra-android-support
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-27
  script:
    - chmod +x ./gradlew
