language: android
jdk:
  - oraclejdk8
android:
  components:
    # Update Android SDK Tools
    - tools
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-27

    # Support library
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    - sys-img-armeabi-v7a-android-27
  script:
    - chmod +x ./gradlew
licenses:
    - 'android-sdk-license-.+'
    - 'android-sdk-preview-license-.+'
    - 'google-gdk-license-.+'
before_install:
  - yes | sdkmanager "platforms;android-27"
